### ISSUE TITLE
WebView / Google API issue

### ISSUE THREAD

**Issue by Aulig** [PixelExperience-Devices/device_xiaomi_raphael#3]
Im getting issues when developing a flutter app that uses a webview, sometimes (I'd say 2/3 of the time when starting the app) I get this error:
E/WebViewFactory( 9197): Chromium WebView package does not exist
E/WebViewFactory( 9197): android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.os.DeadObjectException

After that the whole device freezes and I have to force reboot. Sometimes everything works completely fine though, so Im not sure what's causing it. But I suspect its an issue in one of the last 2 or so pixel experience updates, as everything was fine before. Did you change anything related to google apps or google apis? As https://georgik.rocks/android-emulator-application-crash-chromium-webview-package-does-not-exist/ suggests that it's a google api issue. Downgrading chrome and the webview app to system default didnt help either.

Do you have any idea what could be the issue? If it helps you, I can also upload my debug apk.

Full Stacktrace:
`
Syncing files to device Mi 9T Pro...
E/WebViewFactory(16636): Chromium WebView package does not exist
E/WebViewFactory(16636): android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.os.DeadObjectException
E/WebViewFactory(16636): 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:389)
E/WebViewFactory(16636): 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
E/WebViewFactory(16636): 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
E/WebViewFactory(16636): 	at android.webkit.WebView.getFactory(WebView.java:2559)
E/WebViewFactory(16636): 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2553)
E/WebViewFactory(16636): 	at android.webkit.WebView.setOverScrollMode(WebView.java:2621)
E/WebViewFactory(16636): 	at android.view.View.<init>(View.java:5179)
E/WebViewFactory(16636): 	at android.view.View.<init>(View.java:5320)
E/WebViewFactory(16636): 	at android.view.ViewGroup.<init>(ViewGroup.java:675)
E/WebViewFactory(16636): 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
E/WebViewFactory(16636): 	at android.webkit.WebView.<init>(WebView.java:410)
E/WebViewFactory(16636): 	at android.webkit.WebView.<init>(WebView.java:353)
E/WebViewFactory(16636): 	at android.webkit.WebView.<init>(WebView.java:336)
E/WebViewFactory(16636): 	at android.webkit.WebView.<init>(WebView.java:323)
E/WebViewFactory(16636): 	at android.webkit.WebView.<init>(WebView.java:313)
E/WebViewFactory(16636): 	at io.flutter.plugins.webviewflutter.InputAwareWebView.<init>(InputAwareWebView.java:32)
E/WebViewFactory(16636): 	at io.flutter.plugins.webviewflutter.FlutterWebView.<init>(FlutterWebView.java:45)
E/WebViewFactory(16636): 	at io.flutter.plugins.webviewflutter.WebViewFactory.create(WebViewFactory.java:29)
E/WebViewFactory(16636): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:174)
E/WebViewFactory(16636): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
E/WebViewFactory(16636): 	at android.app.Dialog.show(Dialog.java:315)
E/WebViewFactory(16636): 	at android.app.Presentation.show(Presentation.java:250)
E/WebViewFactory(16636): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
E/WebViewFactory(16636): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:53)
E/WebViewFactory(16636): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:105)
E/WebViewFactory(16636): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/WebViewFactory(16636): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/WebViewFactory(16636): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/WebViewFactory(16636): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/WebViewFactory(16636): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/WebViewFactory(16636): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/WebViewFactory(16636): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/WebViewFactory(16636): 	at android.os.Looper.loop(Looper.java:174)
E/WebViewFactory(16636): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/WebViewFactory(16636): 	at java.lang.reflect.Method.invoke(Native Method)
E/WebViewFactory(16636): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/WebViewFactory(16636): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/MethodChannel#flutter/platform_views(16636): Failed to handle method call
E/MethodChannel#flutter/platform_views(16636): android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.os.DeadObjectException
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebView.getFactory(WebView.java:2559)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2553)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebView.setOverScrollMode(WebView.java:2621)
E/MethodChannel#flutter/platform_views(16636): 	at android.view.View.<init>(View.java:5179)
E/MethodChannel#flutter/platform_views(16636): 	at android.view.View.<init>(View.java:5320)
E/MethodChannel#flutter/platform_views(16636): 	at android.view.ViewGroup.<init>(ViewGroup.java:675)
E/MethodChannel#flutter/platform_views(16636): 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebView.<init>(WebView.java:410)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebView.<init>(WebView.java:353)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebView.<init>(WebView.java:336)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebView.<init>(WebView.java:323)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebView.<init>(WebView.java:313)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.plugins.webviewflutter.InputAwareWebView.<init>(InputAwareWebView.java:32)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.plugins.webviewflutter.FlutterWebView.<init>(FlutterWebView.java:45)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.plugins.webviewflutter.WebViewFactory.create(WebViewFactory.java:29)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:174)
E/MethodChannel#flutter/platform_views(16636): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
E/MethodChannel#flutter/platform_views(16636): 	at android.app.Dialog.show(Dialog.java:315)
E/MethodChannel#flutter/platform_views(16636): 	at android.app.Presentation.show(Presentation.java:250)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:53)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:105)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter/platform_views(16636): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter/platform_views(16636): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(16636): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter/platform_views(16636): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#flutter/platform_views(16636): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#flutter/platform_views(16636): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(16636): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/MethodChannel#flutter/platform_views(16636): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/MethodChannel#flutter/platform_views(16636): Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.os.DeadObjectException
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:389)
E/MethodChannel#flutter/platform_views(16636): 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
E/MethodChannel#flutter/platform_views(16636): 	... 35 more
E/MethodChannel#flutter/platform_views(16636): Failed to handle method call
E/MethodChannel#flutter/platform_views(16636): DeadSystemException: The system died; earlier logs will point to the root cause
E/MethodChannel#flutter/platform_views(16636): Failed to handle method call
E/MethodChannel#flutter/platform_views(16636): DeadSystemException: The system died; earlier logs will point to the root cause
E/flutter (16636): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.os.DeadObjectException, null)
E/flutter (16636): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (16636): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (16636): <asynchronous suspension>
E/flutter (16636): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (16636): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (16636): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (16636): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (16636): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (16636): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #11     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (16636): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #17     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (16636): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #19     RenderAnimatedSize.performLayout (package:flutter/src/rendering/animated_size.dart:182:11)
E/flutter (16636): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #22     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter (16636): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #24     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (16636): #25     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (16636): #26     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (16636): #27     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (16636): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #32     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter (16636): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #34     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (16636): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #36     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
E/flutter (16636): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #42     RenderProxyBoxMixin.perf
E/flutter (16636): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, android.os.DeadSystemException, null)
E/flutter (16636): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (16636): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (16636): <asynchronous suspension>
E/flutter (16636): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (16636): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (16636): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (16636): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (16636): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (16636): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #11     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (16636): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #17     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:544:15)
E/flutter (16636): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #19     RenderAnimatedSize.performLayout (package:flutter/src/rendering/animated_size.dart:182:11)
E/flutter (16636): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #22     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter (16636): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #24     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (16636): #25     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (16636): #26     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (16636): #27     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (16636): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #32     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter (16636): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #34     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (16636): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #36     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
E/flutter (16636): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #43     RenderObject.layout (pa
E/flutter (16636): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, android.os.DeadSystemException, null)
E/flutter (16636): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (16636): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (16636): <asynchronous suspension>
E/flutter (16636): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (16636): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (16636): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (16636): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (16636): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (16636): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #11     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (16636): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #13     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3166:14)
E/flutter (16636): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #15     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
E/flutter (16636): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #32     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3168:13)
E/flutter (16636): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #34     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (16636): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16636): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16636): #44     RenderProxyBoxMix
D/AndroidRuntime(16636): Shutting down VM
E/AndroidRuntime(16636): FATAL EXCEPTION: main
E/AndroidRuntime(16636): Process: me.aulig.web2app, PID: 16636
E/AndroidRuntime(16636): DeadSystemException: The system died; earlier logs will point to the root cause
I/Process (16636): Sending signal. PID: 16636 SIG: 9
Lost connection to device.
`

**Comment by Aulig** [comment]
any ideas on what the issue could be? I really like pixelexperience, but this is a dealbreaker for me unfortunately. I'd love to hear if you have any ideas on what the problem could be @jhenrique09

**Comment by jhenrique09** [comment]
Gonna investigate

**Comment by Aulig** [comment]
Awesome, thank you! I've attached the apk (had to zip it because github doesn't allow .apk) causing the problem, maybe itd be good if you test if you can reproduce the issue even, i dont want to waste your time with it if it for some reason is indeed just an issue with my device. Usually about every 2nd time I open the app it either freezes my phone while its still on the splash screen or a few seconds into using it (just tapping a few buttons).
[app-release.zip](https://github.com/PixelExperience-Devices/device_xiaomi_raphael/files/4434105/app-release.zip)

**Comment by jhenrique09** [comment]
No issues here, check if you're using any module or something else.

**Comment by Aulig** [comment]
Did you close and reopen the app a few times? it doesn't occur every time. But I guess its my device then, but it's weird because the app used to work on my phone and still works in an emulator too. Anyways thanks for checking it out!

**Comment by Aulig** [comment]
Well I switched to lineageos now and its crashing my device there too. Sorry that I wasted your time. Any clue what could be the issue? I formatted data and flashed miui, vendor & then the rom.

Actually I just uninstalled magisk and can't reproduce it anymore (for now, I kind of doubt that this was the issue as it used to work just fine with the same version of magisk)
