### ISSUE TITLE
memeui vendor overlaying our perfect rounded corner/status bar overlay

### ISSUE THREAD

**Issue by yankarinRG** [PixelExperience-Devices/device_xiaomi_raphael#9]
Since 13 june build, Pixel Experience for raphael uses miui vendor instead of OSS.
Culprit overlay is **DevicesAndroidOverlay**, located in _/vendor/overlay/DevicesAndroidOverlay.apk_ with package name **com.miui.systemui.overlay.devices.android** and target package **android** is ruining our device tree overlay for rounded corner and status bar.
This overlay only overlays **rounded_corner_radius_bottom**, **rounded_corner_radius_top** and **status_bar_height_portrait** to wrong values, so it's completely safe to remove.
It's impossible to disable this overlay using `cmd overlay disable --user 0 com.miui.systemui.overlay.devices.android` since said overlay is marked as static.
Maybe the delete logic of this package could be implemented in the _updater-script_ file?
As a workaround, go in recovery and manually remove the package (`adb shell rm /vendor/overlay/DevicesAndroidOverlay.apk`), then wipe cache & art/dalvik cache and reboot to system to bring back the perfectly rounded corners and correct status bar height.
Sadly, a lot of users that won't read this will get sh*tty jagged edges and wrong corner assistant path.

**Comment by jhenrique09** [comment]
fixed with vendor_overlay
